[pytest]
testpaths = tests
python_files = test_*.py Buzz*.py
python_classes = Test* Buzz*
python_functions = test_*
addopts = 
    -v
    --tb=short
    --strict-markers
markers =
    smoke: Smoke tests
    regression: Regression tests
    sanity: Sanity tests
    login: Login related tests
    dashboard: Dashboard related tests
    buzz: Buzz related tests